<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <title>CADASTRO</title>
     <link
     href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
     rel="stylesheet">
</head>
<body>
        <#include "navegar.ftlh" />
    <ul>
      <li><a href="/ExibirContados">Cadastrar Contados</a></li>
      <li><a href="/ListarContados">Listar Contados</a></li>
    </ul>

</body>
</html>