<header class="bg-blue-800 p-6 flex items-center justify-between">
  <div class="text-white font-bold text-3xl">CADASTRO DE USUÁRIOS</div>
  <div>
    <ul class="list-none m-0 p-0 flex items-baseline">
      <li class="ml-6"><a href="/" class="text-black-300 text-2xl hover:text-white">Todos os Cadastros</a></li>
      <li class="ml-6"><a href="/novo-cadastro" class="text-black-300 text-2xl hover:text-white">Novo Cadastro</a></li>
    </ul>
  </div>
</header>